# Site settings
title: Como faz no R e Estatística
email: dfalbel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog com dicas e pequenas análises usando R e/ou estatística.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dfalbel.github.io" # the base hostname & protocol for your site
twitter_username: dfalbel
github_username:  dfalbel
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
