project:
  type: website
  output-dir: docs

website:
  title: "dfalbel"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dfalbel
      - icon: twitter
        href: https://twitter.com/dfalbel
  draft-mode: unlinked

format:
  html:
    theme: cosmo
    css: styles.css
    comments:
      giscus: 
        repo: dfalbel/dfalbel.github.io



