---
layout: post
title: 'Prevendo probabilidades em bases balanceadas'
date : 2016-09-22
tags: [stackoverflow]
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Veja o gráfico do número de perguntas com a tag `R` no pt.stackoverflow por mês.
Será que está crescendo?

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(stackr)
stack_search(tagged = "r", site = "pt.stackoverflow", pagesize = 100, num_pages = 5) %>%
  group_by(ano = year(creation_date), mes = month(creation_date)) %>%
  summarise(n = n()) %>%
  mutate(date = ymd(paste(ano, mes, "01"))) %>%
  ggplot(aes(x = date, y = n)) + 
  geom_line() +
  geom_smooth(method = "lm") +
  labs(x = "Mês", y = "Qtd. Perguntas") + 
  scale_x_date(date_breaks = "8 months")
```

Abaixo o código para reproduzir:

```{r, eval=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(stackr)
stack_search(tagged = "r", site = "pt.stackoverflow", pagesize = 100, num_pages = 5) %>%
  group_by(ano = year(creation_date), mes = month(creation_date)) %>%
  summarise(n = n()) %>%
  mutate(date = ymd(paste(ano, mes, "01"))) %>%
  ggplot(aes(x = date, y = n)) + 
  geom_line() +
  geom_smooth(method = "lm") +
  labs(x = "Mês", y = "Qtd. Perguntas") + 
  scale_x_date(date_breaks = "8 months")
```

