---
title: "Extendr data types"
description: |
  A short description of the post.
author:
  - name: Daniel Falbel
draft: true
date: 02-06-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

+--------------------+----------------------------+-------------------+
| SEXP               | Desc                       | Wrapper           |
+--------------------+----------------------------+-------------------+

+=======================+===============================+======================+\| `NILSXP` \| `NULL` \| Nullable \| +-----------------------+-------------------------------+----------------------+ \| `SYMSXP` \| symbols \| Symbol \| +-----------------------+-------------------------------+----------------------+ \| `LISTSXP` \| pairlists \| Pairlist \| +-----------------------+-------------------------------+----------------------+ \| `CLOSXP` \| closures \| Func \| +-----------------------+-------------------------------+----------------------+ \| `ENVSXP` \| environments \| Env \| +-----------------------+-------------------------------+----------------------+ \| `PROMSXP` \| promises \| Promise \| +-----------------------+-------------------------------+----------------------+ \| `LANGSXP` \| language objects \| Lang \| +-----------------------+-------------------------------+----------------------+ \| `SPECIALSXP` \| special functions \| Primitive? \| +-----------------------+-------------------------------+----------------------+ \| `BUILTINSXP` \| builtin functions \| \| +-----------------------+-------------------------------+----------------------+ \| `CHARSXP` \| internal character strings \| Character \| +-----------------------+-------------------------------+----------------------+ \| `LGLSXP` \| logical vectors \| \| +-----------------------+-------------------------------+----------------------+ \| `INTSXP` \| integer vectors \| \| +-----------------------+-------------------------------+----------------------+ \| `REALSXP` \| numeric vectors \| \| +-----------------------+-------------------------------+----------------------+ \| `CPLXSXP` \| complex vectors \| \| +-----------------------+-------------------------------+----------------------+ \| `STRSXP` \| character vectors \| \| +-----------------------+-------------------------------+----------------------+ \| `DOTSXP` \| dot-dot-dot object \| \| +-----------------------+-------------------------------+----------------------+ \| `ANYSXP` \| make "any" args work \| \| +-----------------------+-------------------------------+----------------------+ \| `VECSXP` \| list (generic vector) \| List \| +-----------------------+-------------------------------+----------------------+ \| `EXPRSXP` \| expression vector \| Expr \| +-----------------------+-------------------------------+----------------------+ \| `BCODESXP` \| byte code \| \| +-----------------------+-------------------------------+----------------------+ \| `EXTPTRSXP` \| external pointer \| \|+-----------------------+-------------------------------+----------------------+ \| `WEAKREFSXP` \| weak reference \| \| +-----------------------+-------------------------------+----------------------+ \| `RAWSXP` \| raw vector \| Raw \| +-----------------------+-------------------------------+----------------------+ \| `S4SXP` \| S4 classes not of simple type \| \| +-----------------------+-------------------------------+----------------------+

## Wrappers

Wrappers are lightweight proxies for references to R data types. There are wrappers for each one of the SEXP types available in R.

### Symbols

``` {.rust}
/// Integer vector from Rust
///
/// @param x Integer vector
/// @returns Returns an integer vector
/// @export
#[extendr] 
fn integer (x:Int) -> Int {
  x
}
```
